<div class="row">
    <div class="col-4">
        <img src="/BazarTemTudo/imgs/logo.png"/>
    </div>
    <div class="col-8">
        <h1>Todo material para sua casa!</h1>
    </div>
</div>

<div id="menu">
    <p><a href="/BazarTemTudo/produto/catalogo.php">Catálogo</a> | <a href="/BazarTemTudo/categoria/lista.php">Categorias</a> | Usuário: <?= $_SESSION["autenticado"] ?> (<a href="/BazarTemTudo/sair.php">sair</a>)</p>
</div>
